### ISSUE TITLE
Suggestion to manage dependencies

### ISSUE THREAD

**Issue by leonardcser** [csia-pme/a-guide-to-mlops#22]
After having a look at [Poetry](https://python-poetry.org) for python package management, its integration might expand too much the scope of the guides.

Using pip is much more familiar. A possibility would be having three `requirements.txt` files (named accordingly).
- One with variable versions for internal update of the packages for the guides
- Another one autogenerated by the pipeline or before push that freezes the internal requirements. This last one would be split into two requirement files:
  - One containing the main packages (which is also referenced in the docs)
  -  One containing all the rest of the freezed dependencies

**Pros:**
- Update packages over time internally
- Fixes dependencies breaking
- A user of the guides is not cluttered by the pip freeze in the docs

**Cons:**
- A user of the guides will need to pip install two requirement files when initialising the environment

**Comment by ludelafo** [comment]
I would much prefer the usage of Poetry to avoid multiple requirements files and explanations on which files to update for what reasons.

@rmarquis had a third solution in mind if I remember correctly. pyenv maybe?

In my opinion, Poetry is the more mature and easy to explain in the context of this guide. It could then be used in other projects without much difficulty.

**Comment by rmarquis** [comment]
I was actually using `Pipenv` which is functionally similar to Poetry. Poetry is however more modern, faster, and use the `pyproject.toml` format (see PEP 518) unlike pipenv. As far I as could see, there is no good reason to use Pipenv instead of Poetry.

**Comment by leonardcser** [comment]
Closed due to merge #28
