### ISSUE TITLE
Ignore the evaluation directory from Git and track it with DVC

### ISSUE THREAD

**Issue by ludelafo** [csia-pme/a-guide-to-mlops#24]
In "Chapter 2: Share your ML experiment code with Git - Create a `.gitignore` file" (https://csia-pme.github.io/a-guide-to-mlops/the-guide/chapter-2-share-your-ml-experiment-code-with-git/#create-a-gitignore-file), the `evaluation` directory is not ignored by Git.

The `evaluation` directory could be ignored by Git and tracked by DVC so that all evaluation data is stored in S3 to clean up the repository and help the review of Pull Requests.

This change might impact some other chapters as well.

**Comment by leonardcser** [comment]
Closed due to #28
