### ISSUE TITLE
Improve and update the Python code of the experiment

### ISSUE THREAD

**Issue by ludelafo** [csia-pme/a-guide-to-mlops#37]
The `code` branch (https://github.com/csia-pme/a-guide-to-mlops/tree/code) contains the code used in the guide. The original link (https://dvc.org/doc/start/data-management/pipelines) stated on the branch has been moved to https://dvc.org/doc/start/data-management/data-pipelines.

This code is only a backup of the DVC's Get Started: Data Pipelines guide. The code is available at https://github.com/iterative/example-get-started/tree/main and is generated from the repository https://github.com/iterative/example-repos-dev/tree/master/example-get-started.

I think we could improve the code made by DVC with a contribution to improve readiness with a linter and a little cleanup.

Once the contribution to the DVC repository is made, we could update the code in our repository as well for a clearer and easier approach on the model lifecycle.

**Comment by leonardcser** [comment]
The new source code has been merged into master https://github.com/iterative/example-repos-dev/tree/master/example-get-started.

I am still waiting for them to update the generated repository.

**Comment by ludelafo** [comment]
Done with PR #60 as we moved to another experiment.
