### ISSUE TITLE
Improvements to the homepage

### ISSUE THREAD

**Issue by bchapuis** [csia-pme/a-guide-to-mlops#69]
- [x] We should display the logo of the HES-SO on the homepage.
- [x] We could add a table of contents pointing to the content of the guide between the title ("Classify celestial bodies using MLOps best practices") and the body of text ("Welcome to our comprehensive guide to MLOps!"). My first reflex was to scroll down, which hides the menu.

**Comment by ludelafo** [comment]
I have worked on the first two parts with several improvements (#70) and I can tackle these issues. Have you started to work on any of them?

**Comment by rmarquis** [comment]
No. They are all yours :)
