### ISSUE TITLE
Continuous deployment of the model with MLEM and the CI/CD pipeline

### ISSUE THREAD

**Issue by ludelafo** [csia-pme/a-guide-to-mlops#80]
Based on the work of #74, add a new 13th chapter "Continuous deployment of the model with MLEM and the CI/CD pipeline" (move the current 13th chapter "Chapter 13 - Train the model on a Kubernetes pod with CML" to "Chapter 14 - Train the model on a Kubernetes pod with CML").

This chapter will deploy the model using MLEM with the CI/CD pipeline for a "true" continuous deployment (CD) pipeline.

**Comment by leonardcser** [comment]
Done in #81
